### ISSUE TITLE
Cannot read config file .eslintrc.js

### ISSUE THREAD

**Issue by dvmorris** [poetic/stanza#34]
This happens in a newly generated stanza project:

```
Cannot read config file: /Users/dvmorris/nightingale_stanza2/.eslintrc.js
Error: Unexpected token :
/Users/dvmorris/nightingale_stanza2/.eslintrc.js:2
  "extends": "poetic"
           ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/dvmorris/nightingale_stanza2/node_modules/require-uncached/index.js:14:12)
    at loadJSConfigFile (/Users/dvmorris/nightingale_stanza2/node_modules/eslint/lib/config/config-file.js:161:16)
```

My solution was to change `.eslintrc.js` from:
```
{
  "extends": "poetic"
}
```
to: 
```
module.exports = {
  "extends": "poetic"
}
```

**Comment by Chun-Yang** [comment]
Fixed
