### ISSUE TITLE
TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by inestyne** [poetic/stanza#52]
os: Ubuntu 16.04 LTS
node -v: v6.4.0
metor --version: Meteor 1.4.1.1

-> stanza update

===== Regenerate images
rm -rf public/images
mkdir -p public/images
cp .design/images/* public/images
cp: no such file or directory: .design/images/*
===== Regenerate css
mkdir -p client/css
mkdir -p client/css/lib
create client/css/main.css from html head
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at readOneHtml (/usr/local/lib/node_modules/poetic-stanza/lib/helpers/read-one-html.js:6:13)
    at copyCss (/usr/local/lib/node_modules/poetic-stanza/lib/update/copy-css.js:30:38)
    at update (/usr/local/lib/node_modules/poetic-stanza/lib/update/index.js:12:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/poetic-stanza/bin/stanza-update.js:13:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

**Comment by Chun-Yang** [comment]
Hey @inestyne You need a webflow project named `design.zip` in the directory.

**Comment by inestyne** [comment]
for some reason i though it was the name of the folder, that worked thank you!
